spring:
   application:
      name: hyperbank-config-provider
      version: 1.0.0
   profiles:
      active: aws-secretmanager, awss3
      include: env_aws, config_main
   cloud:
      config:
         server:
            prefix: /config
            native.search-location: cloud_config
            bootstrap: true
            failOnCompositeError: true
   aws-secretmanager:
      region: eu-west-1
      prefix: 
      order: 1
   awss3:
      region: eu-west-1
      bucket: 
      order: 2

server.port: ${services.hyperbank-config-provider.port}
         

      
         