spring:
   application:
      name: hyperbank-config-provider
      version: 1.0.0
   profiles:
      active: native
      include: config_main
   cloud:
      config:
         server:
            native:
               search-locations: cloud_config
            prefix: /config
            bootstrap: true

server.port: ${env.services-server-port.hyperbank-config-provider}