spring:
   application:
      name: hyperbank-config-provider
      version: 1.0.0
   profiles:
      active: native
      include: env_docker, config_main
   cloud:
      config:
         server:
            native:
               search-locations: cloud_config
            prefix: /config
            bootstrap: true

server.port: ${services.hyperbank-config-provider.port}

logging.config: ./cloud_config/application-config_log4j2-spring.yaml