spring:
   application:
      name: config-provider
      version: 1.0.0
   profiles:
      active: native
   cloud:
      config:
         server:
            native:
               search-locations: cloud_config
            prefix: /config
            bootstrap: true

server.port: 8888