spring:
  application:
    name: hyperbankbanks
    version: 1.0.0
  banner:
    location: classpath:banner.txt
  datasource:
    url: jdbc:postgresql://localhost:5432/HyperBankDB
    driverClassName: org.postgresql.Driver
    username: "paulmarcelinbejan"
    password: "#PaulMarcelinBejanDB!"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.postgresql.Driver
    show-sql: 'true'
    hibernate:
      ddl-auto: update
server:
  port: '9777'
springdoc:
  pathsToMatch: /**
  swagger-ui:
    path: /swagger-ui.html
feign:
  client:
    config:
      default:
        readTimeout: '5000'
        connectTimeout: '5000'
        loggerLevel: basic
logging:
  level:
    com:
      hyperbank:
        banks:
          feignclient: DEBUG