endpoints:
   sql:
      HyperBankDB:
         host: host.aws
         port: 5432
         name: HyperBankDB
         username: myawsusername
         password: myawssecret
   nosql:
      HyperBankMongoDB:
         host: host.aws
         port: 27017
         name: HyperBankMongoDB
         username: myawsusername
         password: myawssecret
         authentication-database: admin
#   cache:
#      CACHE_NAME:
#         host:
#         port: 
#         password: 
#         ssl:
#            enabled: false
#            enablePeerVerification: false
#   messagebroker:
#      MB_NAME:
#         host:
#         port:
services:
   hyperbank-config-provider:
      port: 8888
   hyperbank-accounts:
      port: 9001
   hyperbank-banks:
      port: 9002
   hyperbank-interests:
      port: 9003
   hyperbank-loans:
      port: 9004
   hyperbank-maps:
      port: 9005
   hyperbank-staff:
      port: 9006
   hyperbank-transactions:
      port: 9007
   hyperbank-types:
      port: 9008