spring:
   datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://${endpoints.sql.HyperBankDB.host}:${env.endpoints.sql.HyperBankDB.port}/${env.endpoints.sql.HyperBankDB.name}
      username: ${endpoints.sql.HyperBankDB.username}
      password: ${endpoints.sql.HyperBankDB.password}
   jpa:
      database-platform: org.postgresql.Driver
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc:
               time_zone: Europe/Rome
            format_sql: true
      show-sql: true
      hibernate:
         ddl-auto: update