log4j2.Configuration.allowedProtocols: "http,https"
logging.config: http://${CONFIG_PROVIDER_HOST:localhost}:${CONFIG_PROVIDER_PORT:8888}/config/hyperbank-config-provider/application-config_log4j2-spring.yaml

endpoints:
   sql:
      HyperBankDB:
         host: hyperbank-postgresql-db
         port: 5432
         name: HyperBankDB
         username: paulmarcelinbejan
         password: HyperBankPassword
#   nosql:
#      DB_NAME:
#         host: 
#         port: 
#         name: 
#         username: 
#         password: 
#   cache:
#      CACHE_NAME:
#         host:
#         port: 
#         password: 
#         ssl:
#            enabled: false
#            enablePeerVerification: false
#   messagebroker:
#      MB_NAME:
#         host:
#         port:
services:
   hyperbank-config-provider:
      port: 8888
   hyperbank-accounts:
      port: 9001
   hyperbank-banks:
      port: 9002
   hyperbank-interests:
      port: 9003
   hyperbank-loans:
      port: 9004
   hyperbank-maps:
      port: 9005
   hyperbank-staff:
      port: 9006
   hyperbank-transactions:
      port: 9007
   hyperbank-types:
      port: 9008