env:
   endpoints:
      sql:
         HyperBankDB:
            host: hyperbank-postgresql-db
            port: 5432
            name: HyperBankDB
            username: paulmarcelinbejan
            password: HyperBankPassword
#      nosql:
#         DB_NAME:
#            host: 
#            port: 
#            name: 
#            username: 
#            password: 
#      cache:
#         CACHE_NAME:
#            host:
#            port: 
#            password: 
#            ssl:
#               enabled: false
#               enablePeerVerification: false
#      messagebroker:
#         MB_NAME:
#            host:
#            port:
   services-server-port:
      hyperbank-config-provider: 8888
      hyperbank-accounts: 9001
      hyperbank-banks: 9002
      hyperbank-interests: 9003
      hyperbank-loans: 9004
      hyperbank-maps: 9005
      hyperbank-staff: 9006
      hyperbank-transactions: 9007
      hyperbank-types: 9008